New url dfd
DataFlowAnalysis/DataFlowAnalysis pull request #155
Opened 2024-05-19 10:55 UTC by 01Parzival10

depends on #https://github.com/DataFlowAnalysis/DFD-Metamodel/pull/8

2024-05-30 15:48 UTC, Entenwilli requested changes
Some project files snuck their way in :wink:

2024-05-30 15:48 UTC, Entenwilli commented on .project
This file should not be included (this causes Eclipse to recognize an additional, non-existing, project)

2024-05-30 15:48 UTC, Entenwilli commented on tests/.project
This file should not be included (this causes Eclipse to recognize an additional, non-existing, project)

2024-06-11 11:17 UTC, Nicolas-Boltz commented
@01Parzival10 Tests are failing. Seems that test models need to be fixed.

2024-06-12 06:27 UTC, Entenwilli commented
There was an `"` missing in the online shop 😉

2024-06-12 06:28 UTC, Entenwilli approved these changes
Now it should work :D

2024-06-12 06:28 UTC, merged