Add documentation for installation in Eclipse and IntelliJ
DataFlowAnalysis/DataFlowAnalysis pull request #230
Opened 2024-12-08 16:56 UTC by Entenwilli

This PR adds instructions in the README.md to set up the data flow analysis with both eclipse and IntelliJ

2024-12-08 16:59 UTC, Entenwilli commented
@sebinside @uuqjz @Nicolas-Boltz @01Parzival10 @BenjaminArp Some feedback on this would be nice. Should I add some pictures for each step?

2024-12-09 15:08 UTC, 01Parzival10 commented
I managed to run the analysis ba referencing it from a new Project.
However, I can seem to get existing projects to run. Eclipse does not recognize the main/test classes

2024-12-09 15:48 UTC, Entenwilli commented
> I managed to run the analysis by referencing it from a new Project. However, I can seem to get existing projects to run. Eclipse does not recognize the main/test classes

Do you mean IntelliJ, or really Eclipse?

2024-12-09 16:12 UTC, Entenwilli commented
I've updated the guide by detailing a few more steps and images. This should hopefully fix it.
Nonetheless, this is valuable feedback, as we should expect users to use the DFA from these instructions

2024-12-09 16:12 UTC, Entenwilli commented
@01Parzival10

2024-12-12 13:52 UTC, sebinside requested changes
I tried to follow the IntelliJ guide but without success. Here are a couple of comments / hints:
* The guide lack an overview that tells less experienced developers (or developers that don't know IntelliJ at all), which steps are required in general
* Many steps lack details are us ambiguous language, e.g., step 2 with "our data flow analysis product" (which product, extracted zip?), "well known location" (which location, does it matter, or just that I know where I put it)
* The pictures help a lot, but are sometimes not enough, e.g., step 5 where you expect the "+" button to be clicked. Also other steps sometimes lack precise information where to look or what to click
* I was not able to understand neither follow step 8 - 11
* The guide ends without showing a final results or showing how to, e.g., execute a test

TL;DR: In its current version, the guide requires a lot of detail knowledge that it should explain to non-experts in the first place :)

2025-01-13 12:04 UTC, Entenwilli commented
I've rephrased the installation instructions. Some tasks are still open:
- [ ] Mention IntelliJ verison 

For which step should I insert more images?

2025-01-21 12:21 UTC, BenjaminArp commented
Setup IntelliJ with nightly and current IntelliJ version in 20 minutes without any issues.

2025-07-01 09:23 UTC, Entenwilli commented
Superseeded by #292

2025-07-01 09:23 UTC, closed without merging