Allow Serialization and Deserialization of DSL from and to String
DataFlowAnalysis/DataFlowAnalysis pull request #231
Opened 2024-12-09 13:07 UTC by Entenwilli

This PR implements a serializer and deserializer for the analysis DSL. It includes the following:
- Serialization of DSL elements from a string
- Comprehensive error messages for parser results
- Deserialization of DSL elements to a string

2024-12-09 15:11 UTC, 01Parzival10 submitted a review, later dismissed
LGTM

2025-01-07 12:23 UTC, 01Parzival10 commented
New tests should be added or existing tests modified to make sure the correct constraints are created from string.

2025-01-13 10:33 UTC, Entenwilli commented
This PR is now ready again!
I've implemented multiple parameterized tests for each part of the DSL to ensure it is working

2025-01-15 13:22 UTC, sebinside requested changes
I propose to add more JavaDoc (I marked some of the locations). One could argue, that the `fromString` functions (and related stuff) is only called in this one use case internally, coming from the web editor. However, it could happen in the future that other extensions use this methods, so they should be documented properly (of course, using copy/paste to a high degree).

2025-01-15 13:22 UTC, sebinside commented on bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/dsl/DFDVertexType.java
> +    public static ParseResult<VertexType> fromString(StringView string) {
In general: At least some Javadoc for such high level methods?

2025-01-15 13:22 UTC, sebinside commented on bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/dsl/PCMVertexType.java
> +    public static ParseResult<VertexType> fromString(StringView string) {
Similar JavaDoc comment

2025-01-15 13:22 UTC, sebinside commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/AnalysisConstraint.java
> +    public static ParseResult<AnalysisConstraint> fromString(StringView string, DSLContextProvider contextProvider) {
Javadoc

2025-01-15 13:22 UTC, sebinside commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/AnalysisConstraint.java
> +    public static ParseResult<SourceSelectors> parseSourceSelector(StringView string, DSLContext context) {
Should this be public?

2025-01-15 13:22 UTC, sebinside commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/ConditionalSelectors.java
> +    public static ParseResult<ConditionalSelectors> fromString(StringView string, DSLContext context) {
JavaDoc

2025-01-15 13:22 UTC, sebinside commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/DataSourceSelectors.java
> +    public static ParseResult<DataSourceSelectors> fromString(StringView string, DSLContext context) {
JavaDoc

2025-01-15 13:22 UTC, sebinside commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/SourceSelectors.java
> +public final class SourceSelectors {
JavaDoc everywhere

2025-01-25 13:28 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/AnalysisConstraint.java
> +    public static ParseResult<SourceSelectors> parseSourceSelector(StringView string, DSLContext context) {
Fixed in [baebd1e](https://github.com/DataFlowAnalysis/DataFlowAnalysis/pull/231/commits/baebd1ee610009d51427f3679bb32169ed644f34)

2025-01-27 10:04 UTC, Nicolas-Boltz commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/context/DSLContext.java
>   * Represents the constraint variable context of one constraint
The naming _DSLContext_ is quite unspecific and this JavaDoc does not make it clearer...
For me the question is why not save the variables in the constraint if they only "exist" and are used for this constraint. I am sure this is a valid design decision, however on first glance it is not fully clear to my why it has been made, what DSLContextKeys are, and so on.
We could discuss impoving the naming (eventhough, it will be hard to come up with something good).

2025-01-27 10:14 UTC, Nicolas-Boltz commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/CharacteristicsSelectorData.java
> +    private static final String DSL_SEPARATOR = ".";
Something to discuss in our next meeting:
Could it make sense for these variables that define DSL syntax to all be defined in a central util class?

My thoughts:
DSL_Keyword is obviously specific to each class, however DSL_DELIMITER = "," is defined multiple times... As we do not use inheritance to keep these consistent, a central DSLSyntaxConstants class/enum could make the code better maintainable/evolution easier.

2025-01-27 10:15 UTC, Nicolas-Boltz commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/DataCharacteristicsSelector.java
> +        boolean inverted = string.getString().startsWith("!");
Inverted symbol  "!" should also be a constant, in this class or at a cental point (see other comment).

2025-01-27 10:16 UTC, Nicolas-Boltz commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VariableConditionalSelector.java
> +			return DSL_KEYWORD + " !" + this.constraintVariable.toString();
"!" -> to a constant.

2025-01-27 10:17 UTC, Nicolas-Boltz commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/variable/ConstraintVariableReference.java
> +            if (string.contains("!")) {
again "inversion symbol"

2025-02-03 10:34 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/variable/ConstraintVariableReference.java
> +            if (string.contains("!")) {
Fixed in 4af89ab15f32

2025-02-03 10:34 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/VariableConditionalSelector.java
> +			return DSL_KEYWORD + " !" + this.constraintVariable.toString();
Fixed in 4af89ab15f32

2025-02-03 10:34 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/DataCharacteristicsSelector.java
> +        boolean inverted = string.getString().startsWith("!");
Fixed in 4af89ab15f32

2025-02-03 10:35 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/selectors/CharacteristicsSelectorData.java
> +    private static final String DSL_SEPARATOR = ".";
I agree, fixed in 4af89ab15f32

2025-02-03 11:37 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/dsl/DFDVertexType.java
> +    public static ParseResult<VertexType> fromString(StringView string) {
Fixed in 745e3a1b5bfb

2025-02-03 11:37 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/dsl/PCMVertexType.java
> +    public static ParseResult<VertexType> fromString(StringView string) {
Fixed in 745e3a1b5bfb

2025-02-03 11:37 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/AnalysisConstraint.java
> +    public static ParseResult<AnalysisConstraint> fromString(StringView string, DSLContextProvider contextProvider) {
Fixed in 745e3a1b5bfb

2025-02-03 11:37 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/ConditionalSelectors.java
> +    public static ParseResult<ConditionalSelectors> fromString(StringView string, DSLContext context) {
Fixed in 745e3a1b5bfb

2025-02-03 11:37 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/DataSourceSelectors.java
> +    public static ParseResult<DataSourceSelectors> fromString(StringView string, DSLContext context) {
Fixed in 745e3a1b5bfb

2025-02-03 11:38 UTC, Entenwilli commented on bundles/org.dataflowanalysis.analysis/src/org/dataflowanalysis/analysis/dsl/SourceSelectors.java
> +public final class SourceSelectors {
Fixed in 745e3a1b5bfb

2025-02-04 12:10 UTC, Nicolas-Boltz approved these changes
LGTM

2025-02-04 12:11 UTC, merged