Allow the execution of the analysis via a CLI
DataFlowAnalysis/DataFlowAnalysis pull request #233
Opened 2024-12-11 10:44 UTC by Entenwilli

This PR implements a CLI for the DFD and PCM analysis. It supports the following modes:
- Interactive mode: The CLI asks for the files on the Standard Input
- Arguments mode: The CLI takes the required parameters from the arguments passed to the binary

2025-01-13 11:06 UTC, Entenwilli commented
The CLI can now be executed with a `.dfadsl` file instead of providing a constraint on the command line

2025-01-13 11:06 UTC, Entenwilli commented
Therefore, this PR is also ready to be reviewed

2025-01-15 13:36 UTC, sebinside submitted a review, later dismissed
Just minor stuff. By now, we do not have test cases for the CLI (neither direct via cmd args nor indirect via the interactive cli). I do not find this critical as this is only UI stuff, with one exception: Are we sure that nothing can break when parsing the constraints? You added many (good!) unit test cases regarding the parsing as such, but can something bad happen in the code calling it?

2025-01-15 13:36 UTC, sebinside commented on bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/interactive/DFDAnalysisCLI.java
> +    public static void main(String[] args) {
JavaDoc that this is a potential entry point to the analysis that can be used for use case x

2025-01-15 13:36 UTC, sebinside commented on bundles/org.dataflowanalysis.analysis.dfd/src/org/dataflowanalysis/analysis/dfd/interactive/DFDAnalysisCLI.java
> +        String dataFlowDiagramPath = scanner.nextLine();
For interactive CLIs, I often see this syntax to show that something is expected:

```
Enter x:
> 
```

2025-01-15 13:36 UTC, sebinside commented on bundles/org.dataflowanalysis.analysis.pcm/src/org/dataflowanalysis/analysis/pcm/interactive/PCMAnalysisCLI.java
> +    public static void main(String[] args) {
Similar JavaDoc comment (see DFD Analysis CLI)

2025-01-25 13:16 UTC, Entenwilli commented
Implemented the requested changes @sebinside

2025-01-27 14:05 UTC, Nicolas-Boltz requested changes

2025-02-04 12:12 UTC, Nicolas-Boltz submitted a review, later dismissed
LGTM

2025-02-04 12:17 UTC, merged